[package]
authors = ["The Cloud Hypervisor Authors"]
edition.workspace = true
name = "vfio-usb-hid"
version = "0.1.0"

[lib]
name = "vfio_usb_hid"

[dependencies]
clap = { workspace = true, features = ["cargo", "wrap_help"] }
env_logger = { workspace = true }
log = { workspace = true }
vfio-bindings = { workspace = true }
vfio_user = { workspace = true }
vfio_user_common = { path = "../vfio_user_common" }

[lints]
workspace = true
